using System;

namespace EasyLOB.Data
{
    /// <summary>
    /// Z Data Dictionary Attribute
    /// </summary>
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = true)]
    public class ZDataDictionaryAttribute : Attribute
    {
        #region Properties

        /// <summary>
        /// Associations (Foreign Keys)
        /// </summary>
        public string[] Associations { get; set; }

        /// <summary>
        /// Collections (Primary Keys)
        /// </summary>
        public string[] Collections { get; set; }

        /// <summary>
        /// Is primary key generated by DBMS ?
        /// </summary>
        public bool IsIdentity { get; set; }

        /// <summary>
        /// Is log enabled ?
        /// </summary>
        public bool IsLog { get; set; }

        /// <summary>
        /// Is search WITHOUT WHERE CLAUSE enabled ?
        /// </summary>
        public bool IsSearch { get; set; }

        /// <summary>
        /// Key Property(ies)
        /// </summary>
        public string[] Keys { get; set; }

        /// <summary>
        /// LINQ OrderBy
        /// </summary>
        public string LINQOrderBy { get; set; }

        /// <summary>
        /// LINQ Where
        /// </summary>
        public string LINQWhere { get; set; }

        /// <summary>
        /// Lookup Property
        /// </summary>
        public string Lookup { get; set; }

        /// <summary>
        /// Records by lookup
        /// </summary>
        public int RecordsByLookup { get; set; }

        /// <summary>
        /// Records by page
        /// </summary>
        public int RecordsByPage { get; set; }

        /// <summary>
        /// Records by search
        /// </summary>
        public int RecordsBySearch { get; set; }

        #endregion Properties

        #region Methods

        public ZDataDictionaryAttribute(
            string[] associations, // [ Property1, Property2, ... ]
            string[] collections, // [ Property1, Property2, ... ]
            bool isIdentity,
            string[] keys, // [ Property1, Property2, ... ]
            string linqOrderBy,
            string linqWhere,
            string lookup, // Property
            bool isLog = false,
            bool isSearch = true,
            int recordsBySearch = 0,
            int recordsByLookup = 0,
            int recordsByPage = 0
        )
        {
            Associations = associations;
            Collections = collections;
            IsIdentity = isIdentity;
            IsLog = isLog;
            IsSearch = isSearch;
            Keys = keys;
            LINQOrderBy = linqOrderBy;
            LINQWhere = linqWhere;
            Lookup = lookup;
            RecordsByLookup = recordsByLookup;
            RecordsBySearch = recordsBySearch;
            RecordsByPage = recordsByPage;
        }

        #endregion Methods
    }
}